### PR TITLE
Issue #32 and Issue #34

### PR DESCRIPTION
**Pull request by swarwick**

### CODE REVIEW

**Comment by iamolever** [comment]
So, are we going to rename parameters or merge as is now?

сб, 9 июн. 2018 г. в 15:41, Viacheslav Kolybelkin <notifications@github.com

**Comment by kolybelkin** [comment]
@swarwick What do you think of that?

**Comment by swarwick** [comment]
Just to be clear, we just need a rename of the methods to add 'MBO' correct?  That seems reasonable to me.

**Comment by kolybelkin** [comment]
Yes, you are right

**Comment by swarwick** [comment]
Done

**Comment by iamolever** [comment]
Thanks, swarwick!

**Pull request merged**
