### PR TITLE
Debug and stats

### PR DESCRIPTION
**Pull request by swarwick**
Adding some debug and info logging for the incremental data flow
Issue 59
Issue 60

### CODE REVIEW

**Comment by swarwick** [comment]
It looks like Travis CI no longer works with JDK8 as it says requires version 9 and up

**Comment by swarwick** [comment]
I tried to upgrade the travis yml file to 9 but I keep getting
Could not determine java version from '9.0.4'.

Is there something in the build scripts which are trying to pull out the JDK version? the version actually has 9.0.4+11 so maybe the "+11" is causing issues? Anyone know with me spending to much time on this build stuff?

**Comment by iamolever** [comment]
Let me look

**Comment by iamolever** [comment]
I suppose the issue is related to our too old gradle wrapper. I'll try to update tomorrow. It seems it also requires update of gherkin integraton

**Comment by iamolever** [comment]
Hi, please try to return back openjdk8 in travis and build again

**Pull request closed without merging**
