### PR TITLE
Debug and Stats

### PR DESCRIPTION
**Pull request by swarwick**
Adding some debug and info logging for the incremental data flow
Issue 59
Issue 60

### CODE REVIEW

**Comment by swarwick** [comment]
The travis build still fails out directly 


> Installing oraclejdk8
> $ export JAVA_HOME=~/oraclejdk8
> $ export PATH="$JAVA_HOME/bin:$PATH"
> $ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" 

> --feature "8" --license "BCL"

> Ignoring license option: BCL -- using GPLv2+CE by default
> install-jdk.sh 2019-07-06
> Expected feature release number in range of 9 to 14, but got: 8
> The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
> Your build has been stopped.
>

**Comment by swarwick** [comment]
I just noticed the commit you had done on master 7816caedf2dedb3cc135895125fc1eebff7f668f isnt passing the Travis build either and has the same error.

**Comment by swarwick** [comment]
Could you review the changes I have to go in so that I can at least do an engineering build for our customer and have a bit of confidence we won't have issues down the line by requiring to change this code.

**Comment by iamolever** [comment]
Hi,

don't have time to resolve "NoClassDef" issues in unit tests with later JVM. So as ASAP solution I prefer to remove Travis CI from the project (for temp or forever).

**Comment by iamolever** [comment]
Hi,

I merged and travis is ok to build with java 11 but with disabled unit tests (later should fixed NoClassDef issues in java 9+).

**Pull request merged**
