### PR TITLE
Issue #47 and Issue #48

### PR DESCRIPTION
**Pull request by swarwick**
Added TransactTime to incremental message callback
Added a new Incremental complete callback

### CODE REVIEW

**Comment by iamolever** [comment]
What I worry about: step by step we will have too many parameters in callback.
What if to make packet itself as parameter?

**Comment by swarwick** [comment]
I thought about that initially but was not sure if the team would go for that since it was not done initially (any reason why?) so I ended up following the pattern given.  If the team thinks its better to maybe remove all the parameters and just send in the packet itself I will correct the code and do that.  I personally think in the long run its a much better option so we dont have to modify the callback again in the future if CME adds another top level variable.

**Comment by iamolever** [comment]
I like idea to have packet in callback's context now. @kolybelkin , what's your opinion?

**Comment by kolybelkin** [comment]
> I like idea to have packet in callback's context now. @kolybelkin , what's your opinion?

agree

**Comment by swarwick** [comment]
I will remove this pull request and update to use the full packet in the callback and also update the minor version to 2.1.0 to denote a change to an interface and make sure to mark that in the release notes.

**Comment by iamolever** [comment]
> I will remove this pull request and update to use the full packet in the callback and also update the minor version to 2.1.0 to denote a change to an interface and make sure to mark that in the release notes.

Great, thanks!

**Pull request closed without merging**
