### PR TITLE
remove the loop check method and replace with maintaining index

### PR DESCRIPTION
**Pull request by swarwick**
Please review the changes I made closely. I have added 2 more tests also to cover off more edge cases with adding and remove data from the buffer to make sure things stay in order and are remove correctly according to msg seq number.

### CODE REVIEW

**Comment by swarwick** [comment]
Note removing the check for first position and maintaining an index improves performance by about 25%

**Comment by iamolever** [comment]
Hi Steven,

Thanks for the contribution! Your code above looks okay.
@swarwick, @kolybelkin , did you think about to do not have sort() here at all?
let's suppose we have array list [0 ... 1000].
Let's also suppose we have first inserted package with seqNum=200000.
So we have cases:
1) Normal flow: add(seqNum > 200000). Then we have idx = seqNum = data[0].seqNum;
2) Exceptional flow: we received old packet: add (secNum < 200000 ). Then we can insert first entries (exceptional case). We can even resize (if last entries were are not empty).
3) As for old issues with duplicates: when you calculated index as seqNum = data[0].seqNum you can find that slot is already busy and ignore packet.

**Comment by swarwick** [comment]
Ya we could do something like I think what you specified meaning the index of the current packet would be the msgseq of the first packet minus the current packet
If first packet is 1 (index=0) and current packet is 6 then the index = 0 + (6 - 1) = 5
So for dealing with the buffer being full and kicking out the oldest packet we would have to do something like the remove method is doing right now in that we copy the entire buffer from index 1 to data.length to the first position to kick out the oldest and then deal with the new incoming packet from that point (assuming the new incoming is greater seq num than the oldest packet in the buffer).

**Comment by swarwick** [comment]
One problem I just thought about though would be adding a message that is older than the first message in the buffer which could happen on startup while waiting for sync.. you could get packet 3 and then 2 from the incremental feed so it needs to be able to handle that situation.

**Comment by swarwick** [comment]
It does start to get fairly complex right away without sorting and I am not sure its worth the extra logic to control the positioning for the speed impact of a sort.

There are a few complex situations like:
Buffer size of 5 then packets come into the buffer in this order
7,1,5,6,3,2,4
7 would initially be set to index 0? or 4?
If its set to 0 then when we see packet 1 comes in we need to move 7 six positions up but we also need logic to make sure it doesnt go over the limit, and if it would then we toss 1 as being to old as it would push 7 off the end?

**Comment by swarwick** [comment]
Remove also doesnt work as well because you dont know what to remove. If you added packets 1,3 in current logic it would sort those as side by side, but using and index based they would have a blank packet between then and then you get into logic of looping to find the next non-empty packet anyways.

**Comment by swarwick** [comment]
I added one more change to the sort so it only sorts from 0 to index which is the actual data in the buffer or if full the nthe entire thing which increases the performance considerably

**Comment by iamolever** [comment]
Yes, your thoughts are correct locally, I mean if your are implementing generic buffer (queue) with pre-allocated data slots. I looked remove() and its usage ... is it required to remove this way in context of controller goals? Maybe we should iterate all without gaps and clear/reset entire available sequence? Maybe with new message we have all stored sequence without gaps and can handle and just reset entire queue? ...

Anyway, your current changes look correct for an abstract queue implementation. Let's merge it. Thanks, Steven!

**Pull request merged**
